date = new Date()
console.log(date)
console.log(typeof(date))
date = new Date(30000*3600)
console.log(date)
date = new Date(2023,01,23,10,20,10)
console.log(date)
date = new Date("2012-10-10 10:10:10")
console.log(date)
console.log(date.getFullYear())
console.log(date.getMonth())
console.log(date.getDate())
console.log(date.getDay())
console.log(date.getHours())
console.log(date.getMinutes())
console.log(date.getSeconds())
console.log(date.getMilliseconds())
console.log(date.getTime())

date = new Date(date.getTime())
console.log(date)

date.setFullYear(2020)
date.setMonth(2)
date.setDate(2)
date.setMinutes(23)
date.setHours(2)
date.setSeconds(2)
console.log(date)
date.setTime(1349835010000)
console.log(date)